# We require "sudo" since we're running a docker container.
# See: https://docs.travis-ci.com/user/docker/
sudo: required
services:
  - docker

language: python

# This should match the version run by tox.
python:
  - "3.6"

env:
  global:
    - DJANGO_DB_ENGINE=django.db.backends.postgresql
    - DJANGO_DB_NAME=postgres
    - DJANGO_DB_HOST=localhost
    - DJANGO_DB_USER=postgres
    - DJANGO_DB_PASSWORD=mysecret

# Pull and launch the postgres database container.
before_install:
  - docker pull postgres:9.6
  - docker run -d -P -e POSTGRES_PASSWORD=$DJANGO_DB_PASSWORD postgres:9.6
  - docker ps -a

install:
  - pip install tox coveralls

script:
  - tox

after_success:
  - coveralls
